// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/facilitators": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "facilitators"
                ],
                "summary": "ファシリテーター一覧取得",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "ページ番号（1以上）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "件数（1-100）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "loginId"
                        ],
                        "type": "string",
                        "description": "ソートキー",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "ソート順",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "検索キーワード",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/facilitators.ListResponse"
                        },
                        "headers": {
                            "X-Request-Id": {
                                "type": "string",
                                "description": "リクエストID"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "facilitators.Facilitator": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "loginId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "facilitators.ListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/facilitators.Facilitator"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "golang-data-table-api",
	Description:      "ファシリテーター一覧 API（react-data-table-api の Go 移植版）",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
